name: ToNekoBukkitReforged
version: '0.72.1'
main: suki.mrhua269.tnbr.ToNekoBukkitReforged
api-version: '1.21'
authors: [ MrHua269, CrystalNeko ]
description: ToNeko plugin reforged version
folia-supported: true